import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";
import "./ultron-face-fix.css";

const NAV = [["⌂","Dashboard"],["◉","Chat"],["✓","Tasks"],["▣","Files"],["◌","Browser"],["⌘","Code"],["◈","System Tools"],["◇","Memory"],["⚙","Settings"]];
const MODULES = [["AI Brain","ONLINE"],["Voice System","ONLINE"],["Memory Core","ONLINE"],["File System","ONLINE"],["Browser","ONLINE"],["Code Engine","STANDBY"]];
const COMMANDS=["Open my project folder","Analyze this document","Search on the web","Show system performance"];
const QUICK=["YouTube","GitHub","VS Code","Google","Drive","Notion","WhatsApp","LinkedIn"];
function App(){
 const [active,setActive]=useState("Dashboard"); const [command,setCommand]=useState(""); const [listening,setListening]=useState(false); const [time,setTime]=useState(new Date());
 useEffect(()=>{const id=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(id)},[]);
 const dateText=useMemo(()=>time.toLocaleDateString("en-IN",{weekday:"long",day:"2-digit",month:"long",year:"numeric"}),[time]);
 const send=(text=command)=>{if(!text.trim())return;setCommand("");setActive("Chat")};
 return <div className="ultron-app"><div className="scanlines"/>
 <header className="topbar"><div className="brand"><div className="brand-mark"><span>U</span></div><div><div className="brand-name">ULTRON AI <small>v2.0</small></div><div className="brand-sub">Hyper-Intelligent Platform. Your Strategic Quantum-Neural Partner.</div></div></div><div className="top-center"><div className="top-status"><span className="status-dot"/> SYSTEMS ONLINE</div><div className="top-title">ULTRON AI</div></div><div className="top-actions"><div className="system-pill">SECURITY ENFORCED</div><div className="clock"><strong>{time.toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",second:"2-digit",hour12:true})}</strong><span>{dateText}</span></div><div className="window-actions"><span>—</span><span>□</span><span>×</span></div></div></header>
 <div className="dashboard-grid">
 <aside className="left-rail panel"><div className="rail-head">MAIN HUB</div><nav>{NAV.map(([icon,label])=><button key={label} className={active===label?"active":""} onClick={()=>setActive(label)}><span className="nav-icon">{icon}</span><span>{label}</span></button>)}</nav><div className="rail-core"><div className="mini-heading">ULTRON CORE</div><div className="core-orb"><span>U</span></div><strong>STABLE &amp; OPERATIONAL</strong></div><div className="voice-mini"><div className="mini-heading">VOICE STATUS</div><div className="wave">{Array.from({length:18}).map((_,i)=><i key={i} style={{height:`${12+((i*7)%24)}px`}}/>)}</div><span>{listening?"LISTENING...":"STANDBY"}</span></div></aside>
 <main className="center-column"><div className="hero-top"><div><div className="hello">Hello Mukund,</div><div className="hello-sub">Systems online and fully operational. I am ready to assist you.</div></div><div className="core-badge">CORE UPGRADE v2.0</div></div><section className="hero panel"><div className="hero-label left">ULTRON CORE <span>STABLE</span></div><div className="hero-label right">HOLOGRAPHIC DISPLAY <span>ACTIVE</span></div><div className="rings ring-1"/><div className="rings ring-2"/><div className="rings ring-3"/><div className="face-wrap" aria-label="ULTRON reference face"/><div className="platform"><span/><span/><span/></div><div className="hero-bottom-meta"><span>SCAN FRAME 02A</span><span>HOLOGRAPHIC LINK SECURE</span></div></section><section className="chat panel"><div className="section-title"><span>CHAT WITH ULTRON</span><em>LOCAL MODE</em></div><div className="messages"><div className="msg"><div className="msg-avatar">U</div><div><b>ULTRON</b><span>I can help you with file management, web browsing, code execution, data analysis, automation, and much more.</span></div></div><div className="msg user"><div className="msg-bubble">You: What can you do?</div></div></div><div className="command-bar"><input value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Type your command..."/><button onClick={()=>send()}>➤</button></div></section></main>
 <aside className="right-rail"><section className="panel card"><div className="section-title"><span>ACTIVE MODULES</span><em>6 ONLINE</em></div><div className="module-list">{MODULES.map(([name,state])=><div className="module-row" key={name}><span>{name}</span><b className={state==="ONLINE"?"online":"standby"}>{state}</b></div>)}</div></section><section className="panel card summary"><div className="section-title"><span>TODAY'S SUMMARY</span></div>{[["Tasks Completed","12"],["Files Analyzed","8"],["Commands Executed","26"],["Time Saved","2h 15m"]].map(([a,b])=><div className="metric-row" key={a}><span>{a}</span><b>{b}</b></div>)}</section><section className="panel card command-center"><div className="section-title"><span>COMMAND CENTER</span></div><button className={`mic ${listening?"listening":""}`} onClick={()=>setListening(v=>!v)}><div className="mic-icon">◉</div><strong>{listening?"LISTENING...":"TAP TO SPEAK"}</strong></button><div className="mini-heading">SUGGESTED COMMANDS</div>{COMMANDS.map(item=><button className="suggest" key={item} onClick={()=>send(item)}><span>“{item}”</span><b>+</b></button>)}</section><section className="panel card quick"><div className="section-title"><span>QUICK ACCESS</span></div><div className="quick-grid">{QUICK.map(name=><button key={name} onClick={()=>setActive(name)}>{name}</button>)}</div></section><section className="panel card activity"><div className="section-title"><span>SYSTEM ACTIVITY</span><em>Reset</em></div><div className="activity-chart"/>{[["Voice Recognition","Active"],["AI Processing","Active"],["Data Sync","Active"],["Background Tasks","Idle"]].map(([a,b])=><div className="activity-row" key={a}><span>{a}</span><b>{b}</b></div>)}</section></aside></div><footer className="footer"><span>ULTRON AI — Not just an Assistant. Your Strategic Quantum-Neural Partner.</span><span className="secure">◈ Secure | Private | Local</span></footer></div>
}
createRoot(document.getElementById("root")).render(<App/>);
